version: '3.7'

x-default-build:
    &default-build
    build: .

services:
    songadao-brightid-registration-relay-latest:
        << : *default-build
        image: songadao/brightid-registration-relay:latest

    # songadao-brightid-registration-relay-major:
    #     << : *default-build
    #     image: songadao/brightid-registration-relay:1

    # songadao-brightid-registration-relay-minor:
    #     << : *default-build
    #     image: songadao/brightid-registration-relay:1.0

    # songadao-brightid-registration-relay-patch:
    #     << : *default-build
    #     image: songadao/brightid-registration-relay:1.0.1
